### PR TITLE
fix view:cache issue

### LINKED ISSUE #34: php artisan view:cache issue
## Detailed description

`php artisan view:cache` not working

## Context

I have a issue on running `php artisan view:cache` after install this package, It causes the following error:

The "/var/www/vendor/shetabit/payment/src/Provider/resources/views" directory does not exist.

## Possible implementation

i'm using vue and I don't need to publish blade file(s)

### PR DESCRIPTION
**Pull request by alirezamaleky**
## Description

fixed php artisan view:cache

## Motivation and context

fixes #34 
closes #34

### CODE REVIEW

File: src/Provider/PaymentServiceProvider.php [hunk 1]
```diff
@@ -14,7 +14,7 @@ class PaymentServiceProvider extends ServiceProvider
      */
     public function boot()
     {
-        $this->loadViewsFrom(__DIR__.'/resources/views', 'shetabitPayment');
+        $this->loadViewsFrom(__DIR__.'/../../resources/views', 'shetabitPayment');
```
Comment (khanzadimahdi) [inline src/Provider/PaymentServiceProvider.php]: what would happen if we have not published views to resources path?

Comment (alirezamaleky) [reply src/Provider/PaymentServiceProvider.php]: I just fixed the bug, if you wouldn't have blade file you can remove blade register codes from this file

Comment (khanzadimahdi) [reply src/Provider/PaymentServiceProvider.php]: i mean what would happen if a user has not published views using `vendor:publish` ? if we load views from `resources/views` path, it can cause fetal errors.

Comment (alirezamaleky) [reply src/Provider/PaymentServiceProvider.php]: No, I haven't published views and I don't get error, I test it after publishing views and again nothing happened

Comment (khanzadimahdi) [reply src/Provider/PaymentServiceProvider.php]: which drivers do you use?

Comment (khanzadimahdi) [reply src/Provider/PaymentServiceProvider.php]: i think your solution is not a good one. by default, package views must be loaded from it self directory. loading views from project `resources/views` path it not a good solution.

how ever let me see some famous packages and check them. if they use this solution too, i will merge your pull request.

Comment (khanzadimahdi) [reply src/Provider/PaymentServiceProvider.php]: oh i miss understood! you load it from the package. the address was wrong.

i merge it now.

thanks for your contribution.

Comment (alirezamaleky) [reply src/Provider/PaymentServiceProvider.php]: It is my pleasure
